cite 'about-alias'
about-alias 'common svn abbreviations'

# Aliases
alias st='svn status | less'
alias sa='svn add'
alias sc='svn commit'
alias sci='svn ci -m'
alias sco='svn co'
alias sup='svn up'
alias scu='svn cleanup'
alias sli='svn list'
alias sdel='svn delete'
alias sdl='svn diff | less'
alias sd='svn diff'
alias slog='svn log'
alias smv='svn move'